require('config.neovide')
require('config.options')
require('config.keymaps')
require('config.lsp')
require('config.lazy')
require('config.autocmds')
require('utils.keymap-functions')
require('utils.git')
