require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.telescope"
require "user.treesitter"
require "user.gitlinker"
require "user.gitsigns"
require "user.autopairs"
require "user.comment"
require "user.nvim-lastplace"
require "user.nvim-tree"
require "user.lsp.null-ls"

vim.cmd("hi NonText gui=bold,italic guifg=#AEAFAD")
