" Generated by vim-plug
" Mon 02 Nov 2020 12:26:20 AM MST
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['Dockerfile.vim'].commit = '038480563ce04c5b5e233c5ff6044db2a0760625'
silent! let g:plugs['ack.vim'].commit = '36e40f9ec91bdbf6f1adf408522a73a6925c3042'
silent! let g:plugs['ale'].commit = '557a1ed5da70cb443a8650766f4e8ea95e8c0da3'
silent! let g:plugs['bufexplorer'].commit = '29258f58357acc10c672585a9efe8913d756734d'
silent! let g:plugs['ctrlp.vim'].commit = '3866ae170a342fb40d83e1538c37c81c7977b821'
silent! let g:plugs['gruvbox'].commit = 'bf2885a95efdad7bd5e4794dd0213917770d79b7'
silent! let g:plugs['lightline-ale'].commit = '23352556fdaa067209fa22df424f1b88ab370f6a'
silent! let g:plugs['lightline.vim'].commit = '8769bbb84cd22b475275cc4f9f06a25445357a49'
silent! let g:plugs['nerdtree'].commit = '14af89743ac1c31ff9bb43682025eda50333a7d5'
silent! let g:plugs['tabular'].commit = '339091ac4dd1f17e225fe7d57b48aff55f99b23a'
silent! let g:plugs['ultisnips'].commit = 'e6478871c04bb75f3c6cb9b90e171fffbf9c8ff3'
silent! let g:plugs['vim-auto-origami'].commit = 'eb8c08d12fa7889b53d17072d477f013fb8249a1'
silent! let g:plugs['vim-commentary'].commit = 'f8238d70f873969fb41bf6a6b07ca63a4c0b82b1'
silent! let g:plugs['vim-expand-region'].commit = '966513543de0ddc2d673b5528a056269e7917276'
silent! let g:plugs['vim-fugitive'].commit = '1a77f1c00e12e8460f39098ec3289c5433d32512'
silent! let g:plugs['vim-gitgutter'].commit = '696a6ed389e5b54c8bf480f44ee4e8fc59e6f903'
silent! let g:plugs['vim-instant-markdown'].commit = '2d5324edf171dd0cd2e1eb995fd77816ee3bb959'
silent! let g:plugs['vim-plug'].commit = 'ab940f624ae1df24605a8ff1bf427de7a76e5911'
silent! let g:plugs['vim-repeat'].commit = 'c947ad2b6a16983724a0153bdf7f66d7a80a32ca'
silent! let g:plugs['vim-snippets'].commit = '0161732b61a60a8dc8dd80db7ff678197fc2c2aa'
silent! let g:plugs['vim-startify'].commit = 'f2fc11844b234479d37bef37faa7ceb2aade788b'
silent! let g:plugs['vim-surround'].commit = 'f51a26d3710629d031806305b6c8727189cd1935'
silent! let g:plugs['vim-yankstack'].commit = '157a659c1b101c899935d961774fb5c8f0775370'

PlugUpdate!

