vim.cmd("au! MinimapColorSchemes")
vim.cmd("highlight minimapCursor guibg=#1D1F21 guifg=magenta")
vim.cmd("highlight minimapRange guibg=#282A2E guifg=white")
vim.cmd("highlight minimapDiffAdded guibg=#1D1F21 guifg=#587c0c")
vim.cmd("highlight minimapRemoved guibg=#1D1F21 guifg=#94151b")
vim.cmd("highlight minimapDiffLine guibg=#1D1F21 guifg=#0c7d9d")
vim.cmd("highlight minimapCursorDiffAdded guibg=#1D1F21 guifg=#A4E400")
vim.cmd("highlight minimapCursorDiffRemoved guibg=#1D1F21 guifg=red")
vim.cmd("highlight minimapCursorDiffLine guibg=#1D1F21 guifg=#82A3BF")
vim.cmd("highlight minimapRangeDiffAdded guibg=#282A2E guifg=#587c0c")
vim.cmd("highlight minimapRangeDiffRemoved guibg=#282A2E guifg=#94151b")
vim.cmd("highlight minimapRangeDiffLine guibg=#282A2E guifg=#0c7d9d")
