source ~/.vim/scripts/get_plugins.vim
source ~/.vim/scripts/basic.vim
source ~/.vim/scripts/filetypes.vim
source ~/.vim/scripts/plugins_config.vim
source ~/.vim/scripts/extended.vim

try
source ~/.vim/scripts/my_configs.vim
catch
endtry
